apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    # Client
    - image: ironwagen/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
        # Mode 1: Rebuild image from scratch, update K8S
        # Mode 2: Inject updated files into the Client pod, rely on auto-update.
        # Note that this works only if the project has the ability to detect changes.
        # Client has react, Server and Worker has nodemon
        # Below is mode 2:
        # If any other type of file is changed than specified below, skaffold does mode 1
      sync:
        "**/*.js": .
        "**/*.css": .
        "**/*.html": .

    # Server
    - image: ironwagen/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .

    # Worker
    - image: ironwagen/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml
